language: groovy

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_deploy:
  - touch $HOME/.gradle/gradle.properties
  - echo "gradle.publish.key=${GRADLE_PUBLISH_KEY}" >> $HOME/.gradle/gradle.properties
  - echo "gradle.publish.secret=${GRADLE_PUBLISH_SECRET}" >> $HOME/.gradle/gradle.properties

deploy:
  provider: script
  script: ./gradlew publishPlugins
  on:
    branch: master
